/home/app/workspace/Eggroll_deploy/data
k:b, v:2
k:f, v:20
k:h, v:7
k:i, v:30
lambda ret:[('A_0', 2), ('A_1', 3), ('B_0', 20), ('B_1', 21), ('C_0', 7), ('C_1', 8), ('C_0', 30), ('C_1', 31)]


==== detail start, at 20220808.183554.437 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====




==== detail start, at 20220808.183554.441 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_service.py", line 33, in call
    kwargs=getattr(command_request, '_kwargs'))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 94, in dispatch
    raise e
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError: 

==== detail start, at 20220808.183554.437 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====



==== detail end ====


