[ERROR][2022-08-10 12:52:40,480][eggpair-command-server_1,pid:12257,tid:140093819188992][command_router.py:93.dispatch] - Failed to dispatch to [v1/egg-pair/runTask], task_name: withStores, request: [<ErTask(id=er_session_py_20220810.125209.732_192.168.222.129-py-job-20220810.125240.464968_withStores-task-1, name=withStores, inputs=[<ErPartition(id=1, store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220810.125209.732_192.168.222.129, path=, total_partitions=3, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7f6e17fd95c0>, processor=<ErProcessor(id=5, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=192.168.222.129, port=37735) at 0x7f6e17fd94a8>, transfer_endpoint=<ErEndpoint(host=192.168.222.129, port=43435) at 0x7f6e17fd9d30>, pid=12257, options=[{}], tag=) at 0x7f6e17fd97f0>, rank_in_node=1) at 0x7f6e17fd9390>], outputs=[], job=<ErJob(id=er_session_py_20220810.125209.732_192.168.222.129-py-job-20220810.125240.464968_withStores, name=withStores, inputs=[<ErStore(store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220810.125209.732_192.168.222.129, path=, total_partitions=3, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7f6e17fd9668>, partitions=[***, len=3], options=[{'eggroll.session.processors.per.node': '3', 'total_partitions': '3', 'store_type': 'ROLL_PAIR_CACHE', 'create_if_missing': 'True', 'eggroll.session.id': 'er_session_py_20220810.125209.732_192.168.222.129'}]) at 0x7f6e17fd9198>], outputs=[], functors=[1], options={}) at 0x7f6e17fd99b0>) at 0x7f6e17fd9e80>]
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError: 

==== detail start, at 20220810.125240.479 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====


