[ERROR][2022-08-10 12:52:40,479][eggpair-command-server_1,pid:12246,tid:139913508681472][command_router.py:93.dispatch] - Failed to dispatch to [v1/egg-pair/runTask], task_name: withStores, request: [<ErTask(id=er_session_py_20220810.125209.732_192.168.222.129-py-job-20220810.125240.464968_withStores-task-0, name=withStores, inputs=[<ErPartition(id=0, store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220810.125209.732_192.168.222.129, path=, total_partitions=3, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7f4b984bfcf8>, processor=<ErProcessor(id=4, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=192.168.222.129, port=36223) at 0x7f4b984bfe10>, transfer_endpoint=<ErEndpoint(host=192.168.222.129, port=38453) at 0x7f4b984bf5f8>, pid=12246, options=[{}], tag=) at 0x7f4b984bfac8>, rank_in_node=0) at 0x7f4b984bfa58>], outputs=[], job=<ErJob(id=er_session_py_20220810.125209.732_192.168.222.129-py-job-20220810.125240.464968_withStores, name=withStores, inputs=[<ErStore(store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220810.125209.732_192.168.222.129, path=, total_partitions=3, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7f4b984bf390>, partitions=[***, len=3], options=[{'create_if_missing': 'True', 'eggroll.session.id': 'er_session_py_20220810.125209.732_192.168.222.129', 'eggroll.session.processors.per.node': '3', 'total_partitions': '3', 'store_type': 'ROLL_PAIR_CACHE'}]) at 0x7f4b984bfb38>], outputs=[], functors=[1], options={}) at 0x7f4b984bfba8>) at 0x7f4b984bf7f0>]
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError: 

==== detail start, at 20220810.125240.477 ====
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace/Eggroll_deploy_0/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====


