[ERROR][2022-08-10 13:18:32,211][command_client_1,pid:23892,tid:140294788847360][client.py:96.sync_send] - Error calling to 127.0.0.1:20003, command_uri: CommandURI(_uri=v1/egg-pair/runTask), req:ErCommandRequest(id=20220810.131832.206258, uri=v1/egg-pair/runTask, args=[[b'\nYtest_fs_id_1660108711.1287017_guest_10002-py-job-20220810.131832.202419_withStores-task-0\x12\nwithStores\x1a\xb0\x01\x12h\x12\x0fROLL_PAIR_CACHE\x1a\x0fer_session_meta")test_fs_id_1660108711.1287017_guest_100020\x01:\x0fBYTESTRING_HASHB\x06PICKLE\x1aD\x08\x01\x10\x02"\x08egg_pair*\x07RUNNING2\x0f\n\t127.0.0.1\x10\xa3\x9c\x01:\x0f\n\t127.0.0.1\x10\xa4\x9c\x01H\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\xc8\r\nRtest_fs_id_16'], len=1], kwargs=[***, len=0])
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll/python/eggroll/core/client.py", line 84, in sync_send
    response = _command_stub.call(request.to_proto())
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1660108712.211246083","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1660108712.211238063","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
[ERROR][2022-08-10 13:18:32,480][command_client_1,pid:23892,tid:140294780454656][client.py:96.sync_send] - Error calling to 127.0.0.1:20003, command_uri: CommandURI(_uri=v1/egg-pair/runTask), req:ErCommandRequest(id=20220810.131832.477866, uri=v1/egg-pair/runTask, args=[[b'\nYtest_fs_id_1660108712.2168841_guest_10002-py-job-20220810.131832.474349_withStores-task-0\x12\nwithStores\x1a\xb0\x01\x12h\x12\x0fROLL_PAIR_CACHE\x1a\x0fer_session_meta")test_fs_id_1660108712.2168841_guest_100020\x01:\x0fBYTESTRING_HASHB\x06PICKLE\x1aD\x08\x02\x10\x02"\x08egg_pair*\x07RUNNING2\x0f\n\t127.0.0.1\x10\xa3\x9c\x01:\x0f\n\t127.0.0.1\x10\xa4\x9c\x01H\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\xc8\r\nRtest_fs_id_16'], len=1], kwargs=[***, len=0])
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll/python/eggroll/core/client.py", line 84, in sync_send
    response = _command_stub.call(request.to_proto())
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1660108712.480442047","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1660108712.211238063","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
[ERROR][2022-08-10 13:18:32,708][command_client_1,pid:23892,tid:140294301415168][client.py:96.sync_send] - Error calling to 127.0.0.1:20003, command_uri: CommandURI(_uri=v1/egg-pair/runTask), req:ErCommandRequest(id=20220810.131832.704636, uri=v1/egg-pair/runTask, args=[[b'\nYtest_fs_id_1660108712.4825435_guest_10002-py-job-20220810.131832.699757_withStores-task-0\x12\nwithStores\x1a\xb0\x01\x12h\x12\x0fROLL_PAIR_CACHE\x1a\x0fer_session_meta")test_fs_id_1660108712.4825435_guest_100020\x01:\x0fBYTESTRING_HASHB\x06PICKLE\x1aD\x08\x03\x10\x02"\x08egg_pair*\x07RUNNING2\x0f\n\t127.0.0.1\x10\xa3\x9c\x01:\x0f\n\t127.0.0.1\x10\xa4\x9c\x01H\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\xc8\r\nRtest_fs_id_16'], len=1], kwargs=[***, len=0])
Traceback (most recent call last):
  File "/home/app/workspace/Eggroll/python/eggroll/core/client.py", line 84, in sync_send
    response = _command_stub.call(request.to_proto())
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/app/.venv_eggroll/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1660108712.707308876","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1660108712.211238063","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>
