[ERROR][2022-08-09 17:30:43,884][eggpair-command-server_1,pid:10770,tid:140449180280576][command_router.py:93.dispatch] - Failed to dispatch to [v1/egg-pair/runTask], task_name: withStores, request: [<ErTask(id=er_session_py_20220809.172944.316_192.168.222.129-py-job-20220809.173043.865498_withStores-task-0, name=withStores, inputs=[<ErPartition(id=0, store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220809.172944.316_192.168.222.129, path=, total_partitions=3, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fc4a8d16ba8>, processor=<ErProcessor(id=408, server_node_id=2, name=, processor_type=egg_pair, status=RUNNING, command_endpoint=<ErEndpoint(host=192.168.222.129, port=35197) at 0x7fc4a8d16b00>, transfer_endpoint=<ErEndpoint(host=192.168.222.129, port=35289) at 0x7fc4a8d16160>, pid=10770, options=[{}], tag=) at 0x7fc4a8d16668>, rank_in_node=0) at 0x7fc4a8d16748>], outputs=[], job=<ErJob(id=er_session_py_20220809.172944.316_192.168.222.129-py-job-20220809.173043.865498_withStores, name=withStores, inputs=[<ErStore(store_locator=<ErStoreLocator(id=0, store_type=ROLL_PAIR_CACHE, namespace=er_session_meta, name=er_session_py_20220809.172944.316_192.168.222.129, path=, total_partitions=3, partitioner=BYTESTRING_HASH, serdes=PICKLE) at 0x7fc4a8d16d68>, partitions=[***, len=3], options=[{'eggroll.session.id': 'er_session_py_20220809.172944.316_192.168.222.129', 'eggroll.session.processors.per.node': '3', 'total_partitions': '3', 'store_type': 'ROLL_PAIR_CACHE', 'create_if_missing': 'True'}]) at 0x7fc4a8d16048>], outputs=[], functors=[1], options={}) at 0x7fc4a8d16908>) at 0x7fc4a8d16240>]
Traceback (most recent call last):
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/core/command/command_router.py", line 91, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/core/utils.py", line 194, in wrapper
    raise RuntimeError(msg)
RuntimeError: 

==== detail start, at 20220809.173043.879 ====
Traceback (most recent call last):
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/core/utils.py", line 187, in wrapper
    return func(*args, **kw)
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/roll_pair/egg_pair.py", line 690, in run_task
    value=self.functor_serdes.serialize(f(task)))
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/roll_pair/test/test_roll_pair.py", line 80, in get_eggs
    eggs = input_adapter.get('eggs')
  File "/home/app/workspace_eggroll-2.4.4/Eggroll-2.4.4_deploy/python/eggroll/core/pair_store/adapter.py", line 190, in get
    return self.data[key]
KeyError: 'eggs'

==== detail end ====


